from django.urls import path
from . import views

urlpatterns = [
    path('', views.index_view, name='Index'),
    path('clientes/', views.clientes_view, name='Clientes'),
    path('add_cliente/', views.add_cliente_view, name='AddCliente'),
    path('edit_cliente/', views.edit_cliente_view, name='EditCliente'),
    path('delete_cliente/', views.delete_cliente_view, name='DeleteCliente'),
    path('proveedores/', views.proveedores_view, name='Proveedores'),
    path('add_proveedor/', views.add_proveedor_view, name='AddProveedor'),
    path('edit_proveedor/', views.edit_proveedor_view, name='EditProveedor'),
    path('delete_proveedor/', views.delete_proveedor_view, name='DeleteProveedor'),
    path('productos/', views.productos_view, name='Productos'),
    path('add_producto/', views.add_producto_view, name='AddProducto'),
    path('edit_producto/', views.edit_producto_view, name='EditProducto'),
    path('delete_producto/', views.delete_producto_view, name='DeleteProducto'),
    path('categorias/', views.categorias_view, name='Categorias'),
    path('add_categoria/', views.add_categoria_view, name='AddCategoria'),
    path('edit_categoria/', views.edit_categoria_view, name='EditCategoria'),
    path('delete_categoria/', views.delete_categoria_view, name='DeleteCategoria'),
    path('login/', views.login_view, name='Login'),
    path('logout/', views.logout_view, name='Logout'),
    path('register/', views.register_view, name='Register'),
    path('caja/', views.caja_view, name='caja'),
    path('apertura_caja/', views.caja_view, name='apertura_caja'),
    path('ventas/', views.ventas_view, name='ventas'),
    path('historial-cajas/', views.historial_cajas_view, name='historial_cajas'),
    path('detalle-caja/<int:caja_id>/', views.detalle_caja_view, name='detalle_caja'),
    path('guardar-cliente-ajax/', views.guardar_cliente_ajax, name='guardar_cliente_ajax'),
    path('historial-movimientos/', views.historial_movimientos, name='historial_movimientos'),
    path('ajustes/', views.lista_ajustes, name='lista_ajustes'),
    path('ajustes/crear/', views.crear_ajuste, name='crear_ajuste'),
    path('ajustes/<int:ajuste_id>/', views.detalle_ajuste, name='detalle_ajuste'),
    path('inventarios/', views.lista_inventarios, name='lista_inventarios'),
    path('inventarios/crear/', views.crear_inventario, name='crear_inventario'),
    path('inventarios/<int:inventario_id>/', views.detalle_inventario, name='detalle_inventario'),
    path('transferencias/', views.lista_transferencias, name='lista_transferencias'),
    path('transferencias/crear/', views.crear_transferencia, name='crear_transferencia'),
    path('transferencias/<int:transferencia_id>/completar/', views.completar_transferencia, name='completar_transferencia'),
    path('transferencias/<int:transferencia_id>/cancelar/', views.cancelar_transferencia, name='cancelar_transferencia'),
    path('reservas/', views.lista_reservas, name='lista_reservas'),
    path('reservas/crear/', views.crear_reserva, name='crear_reserva'),
    path('reservas/<int:reserva_id>/cancelar/', views.cancelar_reserva, name='cancelar_reserva'),
    path('reservas/<int:reserva_id>/utilizar/', views.utilizar_reserva, name='utilizar_reserva'),
]