# Generated by Django 4.2.13 on 2025-03-08 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(help_text='Nombre del cliente.', max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('DNI', models.CharField(blank=True, max_length=10, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Direccion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('ImporteTotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaDeAlta', models.DateField()),
                ('FechaDeUltimaModificacion', models.DateField()),
                ('ImporteTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cliente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('pagado', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('ticket', models.BooleanField(default=True)),
                ('desglosar', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', to='ventas.cliente')),
            ],
            options={
                'verbose_name': 'egreso',
                'verbose_name_plural': 'egresos',
                'order_with_respect_to': 'fecha_pedido',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MedioDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('CodigoDeBarras', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=200)),
                ('Cantidad', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('CantidadMinimaSugerida', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('PrecioCosto', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('PrecioDeLista', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('PrecioDeContado', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('FechaUltimaModificacion', models.DateField()),
                ('Marca', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RazonSocial', models.CharField(help_text='Nombre del proveedor.', max_length=50)),
                ('CUIT', models.CharField(max_length=25)),
                ('Tel', models.CharField(max_length=20)),
                ('Email', models.EmailField(default=' ', max_length=254)),
                ('Direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadDeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('NumeroComprobate', models.CharField(max_length=10)),
                ('ImporteTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cliente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
                ('MedioDePago', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.mediodepago')),
                ('detalleVentas', models.ManyToManyField(through='ventas.DetalleVenta', to='ventas.producto')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Categoria', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosEgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=20)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('entregado', models.BooleanField(default=True)),
                ('devolucion', models.BooleanField(default=False)),
                ('egreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.egreso')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
            ],
            options={
                'verbose_name': 'producto egreso',
                'verbose_name_plural': 'productos egreso',
                'order_with_respect_to': 'created',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='Proveedor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='SubCategoria',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.subcategoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='UnidadDeMedida',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.unidaddemedida'),
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('ImporteTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cliente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
                ('MedioDePago', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.mediodepago')),
                ('detalleVentas', models.ManyToManyField(through='ventas.DetallePresupuesto', to='ventas.producto')),
            ],
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='Producto',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.producto'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='Venta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='detallepresupuesto',
            name='Presupuesto',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.presupuesto'),
        ),
        migrations.AddField(
            model_name='detallepresupuesto',
            name='Producto',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.producto'),
        ),
        migrations.CreateModel(
            name='DetalleCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(default=None, null=True)),
                ('Cuenta', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.cuenta')),
                ('Producto', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(default=None, null=True)),
                ('Compra', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.compra')),
                ('Producto', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='detalleCuenta',
            field=models.ManyToManyField(through='ventas.DetalleCuenta', to='ventas.producto'),
        ),
        migrations.AddField(
            model_name='compra',
            name='Proveedor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.proveedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='detalleCompra',
            field=models.ManyToManyField(through='ventas.DetalleCompra', to='ventas.producto'),
        ),
    ]
