# Generated by Django 5.1.3 on 2024-11-30 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(help_text='Nombre del cliente.', max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('DNI', models.CharField(max_length=10)),
                ('Tel', models.CharField(max_length=20)),
                ('Email', models.EmailField(default=' ', max_length=254)),
                ('Direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('ImporteTotal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MedioDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RazonSocial', models.CharField(help_text='Nombre del proveedor.', max_length=50)),
                ('CUIT', models.CharField(max_length=25)),
                ('Tel', models.CharField(max_length=20)),
                ('Email', models.EmailField(default=' ', max_length=254)),
                ('Direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadDeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaDeAlta', models.DateField()),
                ('FechaDeUltimaModificacion', models.DateField()),
                ('ImporteTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cliente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('ImporteTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cliente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
                ('MedioDePago', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.mediodepago')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(default=None, null=True)),
                ('Presupuesto', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.presupuesto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('CodigoDeBarras', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=200)),
                ('Cantidad', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('CantidadMinimaSugerida', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('PrecioCosto', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('PrecioDeLista', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('PrecioDeContado', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('FechaUltimaModificacion', models.DateField()),
                ('Marca', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.marca')),
                ('Proveedor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='detalleVentas',
            field=models.ManyToManyField(through='ventas.DetallePresupuesto', to='ventas.producto'),
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(default=None, null=True)),
                ('Producto', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
            ],
        ),
        migrations.AddField(
            model_name='detallepresupuesto',
            name='Producto',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.producto'),
        ),
        migrations.CreateModel(
            name='DetalleCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(default=None, null=True)),
                ('Cuenta', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.cuenta')),
                ('Producto', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(default=None, null=True)),
                ('Compra', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.compra')),
                ('Producto', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='detalleCuenta',
            field=models.ManyToManyField(through='ventas.DetalleCuenta', to='ventas.producto'),
        ),
        migrations.AddField(
            model_name='compra',
            name='detalleCompra',
            field=models.ManyToManyField(through='ventas.DetalleCompra', to='ventas.producto'),
        ),
        migrations.AddField(
            model_name='compra',
            name='Proveedor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.proveedor'),
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Categoria', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='SubCategoria',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.subcategoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='UnidadDeMedida',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.unidaddemedida'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('NumeroComprobate', models.CharField(max_length=10)),
                ('ImporteTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cliente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
                ('MedioDePago', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.mediodepago')),
                ('detalleVentas', models.ManyToManyField(through='ventas.DetalleVenta', to='ventas.producto')),
            ],
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='Venta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.venta'),
        ),
    ]
