# Generated by Django 4.2.13 on 2025-03-09 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tiempo_reposicion',
            field=models.IntegerField(default=1, help_text='Tiempo en días para reponer el producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ultima_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='ultimo_precio_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='TransaccionInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(choices=[('ENT', 'Entrada'), ('SAL', 'Salida'), ('AJU', 'Ajuste'), ('DEV', 'Devolución')], max_length=3)),
                ('origen_movimiento', models.CharField(choices=[('COM', 'Compra'), ('VEN', 'Venta'), ('AJU', 'Ajuste Manual'), ('DEV', 'Devolución'), ('MER', 'Merma'), ('INI', 'Inventario Inicial')], max_length=3)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('documento_referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.CharField(max_length=50)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='ventas.inventario')),
            ],
            options={
                'verbose_name': 'Transacción de Inventario',
                'verbose_name_plural': 'Transacciones de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50)),
                ('fecha_fabricacion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('cantidad_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_entrada', models.DateField(auto_now_add=True)),
                ('factura_compra', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('CUARENTENA', 'En Cuarentena'), ('VENCIDO', 'Vencido'), ('AGOTADO', 'Agotado')], default='ACTIVO', max_length=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='ventas.producto')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.proveedor')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.AddField(
            model_name='inventario',
            name='producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='ventas.producto'),
        ),
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_ajuste', models.CharField(choices=[('MER', 'Merma'), ('DAÑ', 'Daño'), ('ROB', 'Robo'), ('VEN', 'Vencimiento'), ('ERR', 'Error de Conteo'), ('OTR', 'Otro')], max_length=3)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('justificacion', models.TextField()),
                ('usuario', models.CharField(max_length=50)),
                ('documento_respaldo', models.FileField(blank=True, null=True, upload_to='ajustes/')),
                ('aprobado', models.BooleanField(default=False)),
                ('aprobado_por', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto')),
            ],
            options={
                'verbose_name': 'Ajuste de Inventario',
                'verbose_name_plural': 'Ajustes de Inventario',
                'ordering': ['-fecha'],
            },
        ),
    ]
