# Generated by Django 4.2.13 on 2025-03-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_inventario_producto_activo_producto_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Cantidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='CantidadMinimaSugerida',
        ),
        migrations.AlterField(
            model_name='ajusteinventario',
            name='tipo_ajuste',
            field=models.CharField(choices=[('ENT', 'Entrada'), ('SAL', 'Salida'), ('CNT', 'Conteo')], max_length=3),
        ),
    ]
